name: Production

on:
  push:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Sync with other languages
      uses: unraid/translation-sync-action@master
      with:
        languages: 'nl_NL,es_ES'
        ssh_key_public: ${{ secrets.SSH_PUBLIC_KEY }}
        ssh_key_private: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Run debugging ssh session
      uses: mxschmitt/action-tmate@v2
